language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
 - pylint * || true
 - coverage run --omit *__init__*,*test*,*virtualenv* -m pytest --doctest-modules

after_success:
  - coveralls

